services:
  backend:
    image: dimitri0808/studease-backend:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: dimitri0808/studease-frontend:latest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: